import { FEE_PERCENT } from "@tradejs/core/constants";
import {
  BacktestPriceMode,
  Direction,
  Interval,
  StrategyConfig,
} from "@tradejs/types";

export type GridClassicTakeProfitMode = "center" | "opposite_edge";
export type GridClassicMode = "mean_reversion" | "breakout_continuation";
export type GridClassicEntryConfirmation =
  "rejection" | "close_inside" | "either";

export interface GridClassicSideConfig {
  enable: boolean;
  direction: Direction;
}

type WidenConfigLiteral<Value> = Value extends number
  ? number
  : Value extends boolean
    ? boolean
    : Value;

export const config = {
  ENV: "BACKTEST",
  INTERVAL: "15" as Interval,
  MAKE_ORDERS: true,
  CLOSE_OPPOSITE_POSITIONS: false,
  BACKTEST_PRICE_MODE: "open" as const,
  AI_ENABLED: false,
  AI_MODE: "llm" as const,
  ML_ENABLED: false,
  ML_THRESHOLD: 0.1,
  MIN_AI_QUALITY: 3,
  FEE_PERCENT,
  MAX_LOSS_VALUE: 10,
  MA_FAST: 20,
  MA_MEDIUM: 50,
  MA_SLOW: 100,
  OBV_SMA: 10,
  ATR: 14,
  ATR_PCT_SHORT: 7,
  ATR_PCT_LONG: 30,
  BB: 20,
  BB_STD: 2,
  MACD_FAST: 12,
  MACD_SLOW: 26,
  MACD_SIGNAL: 9,
  GRIDCLASSIC_ATR_PERIOD: 14,
  GRIDCLASSIC_MODE: "mean_reversion" as GridClassicMode,
  GRIDCLASSIC_CONTINUATION_ACCEPTANCE_BARS: 1,
  GRIDCLASSIC_CONTINUATION_RETEST_MAX_BARS: 4,
  GRIDCLASSIC_CONTINUATION_RETEST_TOLERANCE_ATR: 0.3,
  GRIDCLASSIC_CONTINUATION_REQUIRE_DIRECTIONAL_RETEST: false,
  GRIDCLASSIC_CONTINUATION_MAX_ENTRY_DISTANCE_ATR: 0,
  GRIDCLASSIC_CONTINUATION_TARGET_RANGE_MULT: 1,
  GRIDCLASSIC_CONTINUATION_STOP_INSIDE_RANGE_FRACTION: 0.2,
  GRIDCLASSIC_FAILED_BREAKOUT_REVERSAL_ENABLED: false,
  GRIDCLASSIC_PIVOT_LEFT_BARS: 3,
  GRIDCLASSIC_PIVOT_RIGHT_BARS: 3,
  GRIDCLASSIC_LOOKBACK_BARS: 96,
  GRIDCLASSIC_MIN_PIVOTS_PER_SIDE: 3,
  GRIDCLASSIC_MIN_WIDTH_ATR: 3,
  GRIDCLASSIC_MAX_WIDTH_ATR: 14,
  GRIDCLASSIC_MAX_CENTER_SLOPE_ATR_PER_BAR: 0.015,
  GRIDCLASSIC_MAX_BOUNDARY_DIVERGENCE_ATR: 0.8,
  GRIDCLASSIC_MIN_CONTAINMENT_RATIO: 0.9,
  GRIDCLASSIC_CONTAINMENT_TOLERANCE_ATR: 0.2,
  GRIDCLASSIC_BREAKOUT_TOLERANCE_ATR: 0.25,
  GRIDCLASSIC_MIN_RANGE_AGE_BARS: 32,
  GRIDCLASSIC_MAX_VOLATILITY_EXPANSION: 1.8,
  GRIDCLASSIC_MAX_CANDLE_RANGE_ATR: 3,
  GRIDCLASSIC_EDGE_ZONE_FRACTION: 0.12,
  GRIDCLASSIC_ENTRY_CONFIRMATION: "rejection" as GridClassicEntryConfirmation,
  GRIDCLASSIC_MIN_REJECTION_WICK_RATIO: 1.5,
  GRIDCLASSIC_ENTRY_CONFIRMATION_BARS: 1,
  GRIDCLASSIC_MAX_PIVOT_AGE_BARS: 0,
  GRIDCLASSIC_MIN_ALTERNATING_PIVOTS: 0,
  GRIDCLASSIC_RECENT_CONTAINMENT_BARS: 0,
  GRIDCLASSIC_MIN_RECENT_CONTAINMENT_RATIO: 0,
  GRIDCLASSIC_MIN_TARGET_DISTANCE_BPS: 0,
  GRIDCLASSIC_MIN_NET_RISK_RATIO: 0,
  GRIDCLASSIC_LEVELS: 2,
  GRIDCLASSIC_REQUIRE_REJECTION_FOR_ADD: true,
  GRIDCLASSIC_GRID_STEP_ATR: 0.3,
  GRIDCLASSIC_GRID_STEP_RANGE_FRACTION: 0.1,
  GRIDCLASSIC_LEVEL_SIZE_DECAY: 1,
  GRIDCLASSIC_STOP_ATR_BUFFER: 1.5,
  GRIDCLASSIC_TP_MODE: "center" as GridClassicTakeProfitMode,
  GRIDCLASSIC_BREAKOUT_CONFIRM_BARS: 1,
  GRIDCLASSIC_FAILED_REJECTION_EXIT_BARS: 1,
  GRIDCLASSIC_FAILED_REJECTION_TOLERANCE_ATR: 0,
  GRIDCLASSIC_BREAKEVEN_TRIGGER_FRACTION: 0.5,
  GRIDCLASSIC_BREAKEVEN_OFFSET_BPS: 0,
  GRIDCLASSIC_INVALIDATION_BARS: 3,
  GRIDCLASSIC_MAX_HOLD_BARS: 192,
  GRIDCLASSIC_COOLDOWN_BARS: 16,
  GRIDCLASSIC_RISK_SLIPPAGE_BPS: 10,
  GRIDCLASSIC_PROTECTION_REPRICE_ATR: 0.15,
  GRIDCLASSIC_MAX_FIGURE_POINTS: 180,
  LONG: {
    enable: true,
    direction: "LONG",
  },
  SHORT: {
    enable: true,
    direction: "SHORT",
  },
} as const;

type GridClassicRuntimeDefaults = {
  -readonly [Key in keyof typeof config]: WidenConfigLiteral<
    (typeof config)[Key]
  >;
};

export type GridClassicConfig = StrategyConfig &
  Omit<
    GridClassicRuntimeDefaults,
    | "BACKTEST_PRICE_MODE"
    | "GRIDCLASSIC_MODE"
    | "GRIDCLASSIC_ENTRY_CONFIRMATION"
    | "GRIDCLASSIC_TP_MODE"
    | "LONG"
    | "SHORT"
  > & {
    BACKTEST_PRICE_MODE: BacktestPriceMode;
    GRIDCLASSIC_MODE: GridClassicMode;
    GRIDCLASSIC_ENTRY_CONFIRMATION: GridClassicEntryConfirmation;
    GRIDCLASSIC_TP_MODE: GridClassicTakeProfitMode;
    LONG: GridClassicSideConfig;
    SHORT: GridClassicSideConfig;
  };
